environment:
  matrix:
    - nodejs_version: "6.9.2"
      ADDON_VERSION: "48"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install

build: off

after_test:
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] powershell .\\ci\\appveyor\\inno_setup.ps1
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] rd /s /q %APPDATA%\..\Local\NuGet\Cache
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set SRC=%cd%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] echo %SRC%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] copy misc\MSVSVersion.py %APPDATA%\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set NW_VERSION=0.17.6
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set NW_RELEASE=v0.17.6
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] echo %NW_RELEASE%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd node_modules/wotb
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm install --build-from-source
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\wotb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\wotb.node /Y
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd ../naclb
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm install --build-from-source
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\naclb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\naclb.node /Y
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd ../scryptb
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm install --build-from-source
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\scryptb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\scryptb.node /Y
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd ../sqlite3
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm install --build-from-source
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] copy %cd%\lib\binding\node-webkit-%NW_RELEASE%-win32-x64\node_sqlite3.node %cd%\lib\binding\node-v%ADDON_VERSION%-win32-x64\node_sqlite3.node /Y
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd ../..
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm prune --production
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] npm install duniter-ui --save --production
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] rd /s /q %cd%\node_modules\duniter-ui\node_modules
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] cd ..
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] mkdir duniter_release
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set NW=nwjs-%NW_RELEASE%-win-x64
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] echo %NW%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] set NW_GZ=%NW%.zip
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] echo %NW_GZ%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] appveyor DownloadFile https://dl.nwjs.io/%NW_RELEASE%/nwjs-%NW_RELEASE%-win-x64.zip %NW_GZ%
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] 7z x %NW_GZ% 1> null
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] move %NW% %cd%\duniter_release\nw
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] mkdir %cd%\duniter_release\sources
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] xcopy %SRC%\gui\* %cd%\duniter_release\nw\ /s /e
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] xcopy %SRC%\* %cd%\duniter_release\sources\ /s /e
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] iscc %cd%\duniter_release\sources\duniter.iss /DROOT_PATH=%cd%\duniter_release
  - if [%APPVEYOR_REPO_TAG_NAME%] neq [] move %cd%\duniter_release\Duniter.exe %cd%\duniter\duniter-desktop-%APPVEYOR_REPO_TAG_NAME%-windows-x64.exe

artifacts:
  - path: duniter*.exe
    name: Duniter

deploy:
  release: v0.91.3
  provider: GitHub
  auth_token:
    secure: Vp/M0r0i1yhGR2nhrPWEbTiDIF6r0cmwbNDFZUzdFe5clWxPXtuC0lgIpOQI78zt
  artifact: /Duniter/
#  prerelease: true
  on:
    appveyor_repo_tag: true
