environment:
  matrix:
    - nodejs_version: "5.9.1"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install

test_script:
  - npm test

build: off

after_test:
  - rd /s /q %APPDATA%\..\Local\NuGet\Cache
  - choco install -y 7zip InnoSetup
  - set PATH="C:\Program Files\7-Zip";"C:\Program Files (x86)\Inno Setup 5";%PATH%
  # GUI Version
  - set SRC=%cd%
  - echo %SRC%
  - copy misc\MSVSVersion.py %APPDATA%\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py
  - set NW_VERSION=0.14.5
  - set NW_RELEASE=v0.14.5
  - echo %NW_RELEASE%
  - cd node_modules/wotb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\wotb.node %cd%\lib\binding\Release\node-v47-win32-x64\wotb.node /Y
  - cd ../naclb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\naclb.node %cd%\lib\binding\Release\node-v47-win32-x64\naclb.node /Y
  - cd ../scryptb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\scryptb.node %cd%\lib\binding\Release\node-v47-win32-x64\scryptb.node /Y
  - cd ../sqlite3b
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\node_sqlite3.node %cd%\lib\binding\Release\node-v47-win32-x64\node_sqlite3.node /Y
  - cd ../..
  - npm prune --production
  - cd ..
  - mkdir duniter_release
  - set NW=nwjs-%NW_RELEASE%-win-x64
  - echo %NW%
  - set NW_GZ=%NW%.zip
  - echo %NW_GZ%
  - curl -fS -o %NW_GZ% https://s3.eu-central-1.amazonaws.com/duniter/binaries/%NW_GZ%
  - 7z x %NW_GZ% 1> null
  - move %NW% %cd%\duniter_release\nw
  - mkdir %cd%\duniter_release\sources
  - xcopy %SRC%\gui\* %cd%\duniter_release\nw\ /s /e
  - xcopy %SRC%\* %cd%\duniter_release\sources\ /s /e
  - rd /s /q %cd%\duniter_release\sources\ui\package\node_modules
  - rd /s /q %cd%\duniter_release\sources\ui\package\bower_components
  - iscc %cd%\duniter_release\sources\duniter.iss /DROOT_PATH=%cd%\duniter_release
  - move %cd%\duniter_release\Duniter.exe %cd%\duniter\duniter-%APPVEYOR_REPO_TAG_NAME%-windows-x64.exe

artifacts:
  - path: duniter*.exe
    name: Duniter

deploy:
  release: v0.20.0a66
  provider: GitHub
  auth_token:
    secure: Vp/M0r0i1yhGR2nhrPWEbTiDIF6r0cmwbNDFZUzdFe5clWxPXtuC0lgIpOQI78zt
  artifact: /Duniter/
  prerelease: true
  on:
    appveyor_repo_tag: true
