environment:
  matrix:
    - nodejs_version: "5.8.0"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install

test_script:
  - npm test

build: off

after_test:
  - choco install -y wget 7zip InnoSetup
  - set PATH="C:\Program Files\7-Zip";"C:\Program Files (x86)\Inno Setup 5";%PATH%
  # GUI Version
  - set SRC=%cd%
  - echo %SRC%
  - copy misc\MSVSVersion.py %APPDATA%\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py
  - set NW_VERSION=0.13.0-rc3
  - set NW_RELEASE=v0.13.0-rc3
  - echo %NW_RELEASE%
  - cd node_modules/wotb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\wotb.node %cd%\lib\binding\Release\node-v47-win32-x64\wotb.node /Y
  - cd ../naclb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\naclb.node %cd%\lib\binding\Release\node-v47-win32-x64\naclb.node /Y
  - cd ../scryptb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\scryptb.node %cd%\lib\binding\Release\node-v47-win32-x64\scryptb.node /Y
  - cd ../sqlite3b
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\node-webkit-%NW_RELEASE%-win32-x64\node_sqlite3.node %cd%\lib\binding\node-v47-win32-x64\node_sqlite3.node /Y
  - cd ../..
  - npm prune --production
  - cd ..
  - mkdir ucoin_release
  - set NW=nwjs-%NW_RELEASE%-win-x64
  - echo %NW%
  - set NW_GZ=%NW%.zip
  - echo %NW_GZ%
  - wget http://dl.nwjs.io/%NW_RELEASE%/%NW_GZ%
  - 7z x %NW_GZ% 1> null
  - move %NW% %cd%\ucoin_release\nw
  - mkdir %cd%\ucoin_release\sources
  - xcopy %SRC%\gui\* %cd%\ucoin_release\nw\ /s /e
  - xcopy %SRC%\* %cd%\ucoin_release\sources\ /s /e
  - rd /s /q %cd%\ucoin_release\sources\ui\package\node_modules
  - rd /s /q %cd%\ucoin_release\sources\ui\package\bower_components
  - 7z a -tzip duniter-win-x64.zip %cd%\ucoin_release\* 1> null
  - move duniter-win-x64.zip %cd%\ucoin\duniter-%APPVEYOR_REPO_TAG_NAME%-windows-x64.zip
  - iscc %cd%\ucoin_release\sources\duniter.iss /DROOT_PATH=%cd%\ucoin_release
  - move %cd%\ucoin_release\Duniter.exe %cd%\ucoin\duniter-%APPVEYOR_REPO_TAG_NAME%-windows-x64.exe

artifacts:
  - path: duniter*.exe
    name: DuniterEXE
  - path: duniter*.zip
    name: Duniter

deploy:
  release: v0.20.0a18
  provider: GitHub
  auth_token:
    secure: Vp/M0r0i1yhGR2nhrPWEbTiDIF6r0cmwbNDFZUzdFe5clWxPXtuC0lgIpOQI78zt
  artifact: /Duniter/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
